<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>คำนวณอายุตึงๆ</description>
   <name>auto_age</name>
   <tag></tag>
   <elementGuidId>2d55463f-1df3-4008-bd78-3c96740e1d77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;age&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
